---
- hosts: all
  name: init a shelly with default values and gather all information
  gather_facts: false
  connection: local
  roles:
    - shelly-get-gen

  tasks:
  - name: shelly v1 reboot
    ansible.builtin.include_role:
      name: shelly-reboot
    when: shellygen == 1

  - name: shelly v2 reboot
    ansible.builtin.include_role:
      name: shellyV2-reboot
    when: shellygen == "2"
