---
- name: "Wait till shelly {{ inventory_hostname }} is reachable"
  ansible.builtin.uri:
    method: get
    url: "http://{{ inventory_hostname }}/shelly"
  delegate_to: localhost
  register: basicinfo
  retries: 50
  delay: 10
  until: basicinfo is defined and basicinfo.status == 200

- ansible.builtin.set_fact:
    shellyset: "{{ shellyconfig.shellyset }}"
- include_role: 
    name: shellyV2-setloop
  with_dict: "{{ shellyset.data }}"
  loop_control: 
    loop_var: setloop

- ansible.builtin.set_fact:
    shellyset: "{{ wificonfig.shellyset }}"
- include_role: 
    name: shellyV2-setloop
  with_dict: "{{ shellyset.data }}"
  loop_control: 
    loop_var: setloop

- ansible.builtin.set_fact:
    shellyset: "{{ bleconfig.shellyset }}"
- include_role: 
    name: shellyV2-setloopone
  with_dict: "{{ shellyset.data }}"
  loop_control: 
    loop_var: setloopone

- ansible.builtin.set_fact:
    shellyset: "{{ cloudconfig.shellyset }}"
- include_role: 
    name: shellyV2-setloopone
  with_dict: "{{ shellyset.data }}"
  loop_control: 
    loop_var: setloopone

- ansible.builtin.set_fact:
    shellyset: "{{ mqttconfig.shellyset }}"
- include_role: 
    name: shellyV2-setloopone
  with_dict: "{{ shellyset.data }}"
  loop_control: 
    loop_var: setloopone   

- ansible.builtin.set_fact:
    shellysetsingle: "{{ scheduldel.shellyset }}"
- include_role:
    name: shellyV2-set

- ansible.builtin.set_fact:
    shellysetsingle: "{{ webhookdel.shellyset }}"
- include_role:
    name: shellyV2-set     