---

- name: get shelly basic infos
  ansible.builtin.uri:
    method: get
    url: "http://{{ inventory_hostname }}/shelly"
  delegate_to: localhost
  register: shellyinfo

- name: set ShellyGen
  ansible.builtin.set_fact:
    shellygen: 1
  when: shellyinfo.json.gen is not defined      

- name: set ShellyGen if gen 2
  ansible.builtin.set_fact:
    shellygen: "{{ shellyinfo.json.gen }}"
  when: shellyinfo.json.gen is defined  
